---
swagger: "2.0"
info:
  description: "test"
  version: "v1"
  title: "test"
host: "jsonplaceholder.typicode.com"
basePath: "/"
schemes:
- "https"
paths:
  /posts:
    get:
      summary: "Get client IP"
      parameters:
      - name: "id"
        in: "query"
        description: "The format to return the response in, i.e. json."
        required: true
        type: "string"
        default: "1"
      responses:
        200:
          description: "Success response"
definitions: {}
